/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VendorRegisterRouteImport } from './routes/vendor-register'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCompanyRouteImport } from './routes/_authenticated/admin.company'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminPortalRouteImport } from './routes/_authenticated/admin.portal'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedBoqIndexRouteImport } from './routes/_authenticated/boq.index'
import { Route as AuthenticatedBoqBoqIdRouteImport } from './routes/_authenticated/boq.$boqId'
import { Route as AuthenticatedCrmClientsRouteImport } from './routes/_authenticated/crm.clients'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmOpportunitiesRouteImport } from './routes/_authenticated/crm.opportunities'
import { Route as AuthenticatedCrmTendersRouteImport } from './routes/_authenticated/crm.tenders'
import { Route as AuthenticatedDesignIndexRouteImport } from './routes/_authenticated/design.index'
import { Route as AuthenticatedDesignDesignIdRouteImport } from './routes/_authenticated/design.$designId'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedFinanceInvoiceIdRouteImport } from './routes/_authenticated/finance.$invoiceId'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedJarvisIndexRouteImport } from './routes/_authenticated/jarvis.index'
import { Route as AuthenticatedJarvisLogRouteImport } from './routes/_authenticated/jarvis.log'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance.index'
import { Route as AuthenticatedMaintenanceContractsRouteImport } from './routes/_authenticated/maintenance.contracts'
import { Route as AuthenticatedMaintenanceInspectionsRouteImport } from './routes/_authenticated/maintenance.inspections'
import { Route as AuthenticatedMaintenanceIrrigationRouteImport } from './routes/_authenticated/maintenance.irrigation'
import { Route as AuthenticatedMaintenanceIssuesRouteImport } from './routes/_authenticated/maintenance.issues'
import { Route as AuthenticatedMaintenanceSchedulesRouteImport } from './routes/_authenticated/maintenance.schedules'
import { Route as AuthenticatedMaintenanceTasksRouteImport } from './routes/_authenticated/maintenance.tasks'
import { Route as AuthenticatedMaintenanceTemplatesRouteImport } from './routes/_authenticated/maintenance.templates'
import { Route as AuthenticatedMaintenanceTreatmentsRouteImport } from './routes/_authenticated/maintenance.treatments'
import { Route as AuthenticatedMastersMaterialsRouteImport } from './routes/_authenticated/masters.materials'
import { Route as AuthenticatedMastersPlantsRouteImport } from './routes/_authenticated/masters.plants'
import { Route as AuthenticatedNurseryIndexRouteImport } from './routes/_authenticated/nursery.index'
import { Route as AuthenticatedPlantiqIndexRouteImport } from './routes/_authenticated/plantiq.index'
import { Route as AuthenticatedProcurementIndexRouteImport } from './routes/_authenticated/procurement.index'
import { Route as AuthenticatedProcurementPoIdRouteImport } from './routes/_authenticated/procurement.$poId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedSiteIndexRouteImport } from './routes/_authenticated/site.index'
import { Route as AuthenticatedSiteReportIdRouteImport } from './routes/_authenticated/site.$reportId'
import { Route as AuthenticatedTenderBoqIndexRouteImport } from './routes/_authenticated/tender-boq.index'
import { Route as AuthenticatedTenderBoqTenderBoqIdRouteImport } from './routes/_authenticated/tender-boq.$tenderBoqId'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal.index'
import { Route as PortalPortalBillingRouteImport } from './routes/_portal/portal.billing'
import { Route as PortalPortalBillsRouteImport } from './routes/_portal/portal.bills'
import { Route as PortalPortalOrdersRouteImport } from './routes/_portal/portal.orders'
import { Route as PortalPortalProjectsRouteImport } from './routes/_portal/portal.projects'
import { Route as ApiPublicTendersIngestRouteImport } from './routes/api/public/tenders-ingest'
import { Route as AuthenticatedMaintenanceSitesIndexRouteImport } from './routes/_authenticated/maintenance.sites.index'
import { Route as AuthenticatedMaintenanceSitesSiteIdRouteImport } from './routes/_authenticated/maintenance.sites.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor-register',
  path: '/vendor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCompanyRoute =
  AuthenticatedAdminCompanyRouteImport.update({
    id: '/admin/company',
    path: '/admin/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPortalRoute =
  AuthenticatedAdminPortalRouteImport.update({
    id: '/admin/portal',
    path: '/admin/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoqIndexRoute = AuthenticatedBoqIndexRouteImport.update({
  id: '/boq/',
  path: '/boq/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoqBoqIdRoute = AuthenticatedBoqBoqIdRouteImport.update({
  id: '/boq/$boqId',
  path: '/boq/$boqId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmClientsRoute = AuthenticatedCrmClientsRouteImport.update({
  id: '/crm/clients',
  path: '/crm/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmOpportunitiesRoute =
  AuthenticatedCrmOpportunitiesRouteImport.update({
    id: '/crm/opportunities',
    path: '/crm/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmTendersRoute = AuthenticatedCrmTendersRouteImport.update({
  id: '/crm/tenders',
  path: '/crm/tenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignIndexRoute =
  AuthenticatedDesignIndexRouteImport.update({
    id: '/design/',
    path: '/design/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignDesignIdRoute =
  AuthenticatedDesignDesignIdRouteImport.update({
    id: '/design/$designId',
    path: '/design/$designId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceInvoiceIdRoute =
  AuthenticatedFinanceInvoiceIdRouteImport.update({
    id: '/finance/$invoiceId',
    path: '/finance/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJarvisIndexRoute =
  AuthenticatedJarvisIndexRouteImport.update({
    id: '/jarvis/',
    path: '/jarvis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJarvisLogRoute = AuthenticatedJarvisLogRouteImport.update({
  id: '/jarvis/log',
  path: '/jarvis/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceContractsRoute =
  AuthenticatedMaintenanceContractsRouteImport.update({
    id: '/maintenance/contracts',
    path: '/maintenance/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceInspectionsRoute =
  AuthenticatedMaintenanceInspectionsRouteImport.update({
    id: '/maintenance/inspections',
    path: '/maintenance/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceIrrigationRoute =
  AuthenticatedMaintenanceIrrigationRouteImport.update({
    id: '/maintenance/irrigation',
    path: '/maintenance/irrigation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceIssuesRoute =
  AuthenticatedMaintenanceIssuesRouteImport.update({
    id: '/maintenance/issues',
    path: '/maintenance/issues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceSchedulesRoute =
  AuthenticatedMaintenanceSchedulesRouteImport.update({
    id: '/maintenance/schedules',
    path: '/maintenance/schedules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceTasksRoute =
  AuthenticatedMaintenanceTasksRouteImport.update({
    id: '/maintenance/tasks',
    path: '/maintenance/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceTemplatesRoute =
  AuthenticatedMaintenanceTemplatesRouteImport.update({
    id: '/maintenance/templates',
    path: '/maintenance/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceTreatmentsRoute =
  AuthenticatedMaintenanceTreatmentsRouteImport.update({
    id: '/maintenance/treatments',
    path: '/maintenance/treatments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMaterialsRoute =
  AuthenticatedMastersMaterialsRouteImport.update({
    id: '/masters/materials',
    path: '/masters/materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersPlantsRoute =
  AuthenticatedMastersPlantsRouteImport.update({
    id: '/masters/plants',
    path: '/masters/plants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNurseryIndexRoute =
  AuthenticatedNurseryIndexRouteImport.update({
    id: '/nursery/',
    path: '/nursery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantiqIndexRoute =
  AuthenticatedPlantiqIndexRouteImport.update({
    id: '/plantiq/',
    path: '/plantiq/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementIndexRoute =
  AuthenticatedProcurementIndexRouteImport.update({
    id: '/procurement/',
    path: '/procurement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPoIdRoute =
  AuthenticatedProcurementPoIdRouteImport.update({
    id: '/procurement/$poId',
    path: '/procurement/$poId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteIndexRoute = AuthenticatedSiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiteReportIdRoute =
  AuthenticatedSiteReportIdRouteImport.update({
    id: '/site/$reportId',
    path: '/site/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenderBoqIndexRoute =
  AuthenticatedTenderBoqIndexRouteImport.update({
    id: '/tender-boq/',
    path: '/tender-boq/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenderBoqTenderBoqIdRoute =
  AuthenticatedTenderBoqTenderBoqIdRouteImport.update({
    id: '/tender-boq/$tenderBoqId',
    path: '/tender-boq/$tenderBoqId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalBillingRoute = PortalPortalBillingRouteImport.update({
  id: '/portal/billing',
  path: '/portal/billing',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalBillsRoute = PortalPortalBillsRouteImport.update({
  id: '/portal/bills',
  path: '/portal/bills',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalOrdersRoute = PortalPortalOrdersRouteImport.update({
  id: '/portal/orders',
  path: '/portal/orders',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPortalProjectsRoute = PortalPortalProjectsRouteImport.update({
  id: '/portal/projects',
  path: '/portal/projects',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiPublicTendersIngestRoute = ApiPublicTendersIngestRouteImport.update({
  id: '/api/public/tenders-ingest',
  path: '/api/public/tenders-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaintenanceSitesIndexRoute =
  AuthenticatedMaintenanceSitesIndexRouteImport.update({
    id: '/maintenance/sites/',
    path: '/maintenance/sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceSitesSiteIdRoute =
  AuthenticatedMaintenanceSitesSiteIdRouteImport.update({
    id: '/maintenance/sites/$siteId',
    path: '/maintenance/sites/$siteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/boq/$boqId': typeof AuthenticatedBoqBoqIdRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/opportunities': typeof AuthenticatedCrmOpportunitiesRoute
  '/crm/tenders': typeof AuthenticatedCrmTendersRoute
  '/design/$designId': typeof AuthenticatedDesignDesignIdRoute
  '/finance/$invoiceId': typeof AuthenticatedFinanceInvoiceIdRoute
  '/jarvis/log': typeof AuthenticatedJarvisLogRoute
  '/maintenance/contracts': typeof AuthenticatedMaintenanceContractsRoute
  '/maintenance/inspections': typeof AuthenticatedMaintenanceInspectionsRoute
  '/maintenance/irrigation': typeof AuthenticatedMaintenanceIrrigationRoute
  '/maintenance/issues': typeof AuthenticatedMaintenanceIssuesRoute
  '/maintenance/schedules': typeof AuthenticatedMaintenanceSchedulesRoute
  '/maintenance/tasks': typeof AuthenticatedMaintenanceTasksRoute
  '/maintenance/templates': typeof AuthenticatedMaintenanceTemplatesRoute
  '/maintenance/treatments': typeof AuthenticatedMaintenanceTreatmentsRoute
  '/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/procurement/$poId': typeof AuthenticatedProcurementPoIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/site/$reportId': typeof AuthenticatedSiteReportIdRoute
  '/tender-boq/$tenderBoqId': typeof AuthenticatedTenderBoqTenderBoqIdRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/portal/orders': typeof PortalPortalOrdersRoute
  '/portal/projects': typeof PortalPortalProjectsRoute
  '/api/public/tenders-ingest': typeof ApiPublicTendersIngestRoute
  '/boq/': typeof AuthenticatedBoqIndexRoute
  '/design/': typeof AuthenticatedDesignIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/jarvis/': typeof AuthenticatedJarvisIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/nursery/': typeof AuthenticatedNurseryIndexRoute
  '/plantiq/': typeof AuthenticatedPlantiqIndexRoute
  '/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/site/': typeof AuthenticatedSiteIndexRoute
  '/tender-boq/': typeof AuthenticatedTenderBoqIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/maintenance/sites/$siteId': typeof AuthenticatedMaintenanceSitesSiteIdRoute
  '/maintenance/sites/': typeof AuthenticatedMaintenanceSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/boq/$boqId': typeof AuthenticatedBoqBoqIdRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/opportunities': typeof AuthenticatedCrmOpportunitiesRoute
  '/crm/tenders': typeof AuthenticatedCrmTendersRoute
  '/design/$designId': typeof AuthenticatedDesignDesignIdRoute
  '/finance/$invoiceId': typeof AuthenticatedFinanceInvoiceIdRoute
  '/jarvis/log': typeof AuthenticatedJarvisLogRoute
  '/maintenance/contracts': typeof AuthenticatedMaintenanceContractsRoute
  '/maintenance/inspections': typeof AuthenticatedMaintenanceInspectionsRoute
  '/maintenance/irrigation': typeof AuthenticatedMaintenanceIrrigationRoute
  '/maintenance/issues': typeof AuthenticatedMaintenanceIssuesRoute
  '/maintenance/schedules': typeof AuthenticatedMaintenanceSchedulesRoute
  '/maintenance/tasks': typeof AuthenticatedMaintenanceTasksRoute
  '/maintenance/templates': typeof AuthenticatedMaintenanceTemplatesRoute
  '/maintenance/treatments': typeof AuthenticatedMaintenanceTreatmentsRoute
  '/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/procurement/$poId': typeof AuthenticatedProcurementPoIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/site/$reportId': typeof AuthenticatedSiteReportIdRoute
  '/tender-boq/$tenderBoqId': typeof AuthenticatedTenderBoqTenderBoqIdRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/portal/orders': typeof PortalPortalOrdersRoute
  '/portal/projects': typeof PortalPortalProjectsRoute
  '/api/public/tenders-ingest': typeof ApiPublicTendersIngestRoute
  '/boq': typeof AuthenticatedBoqIndexRoute
  '/design': typeof AuthenticatedDesignIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/jarvis': typeof AuthenticatedJarvisIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/nursery': typeof AuthenticatedNurseryIndexRoute
  '/plantiq': typeof AuthenticatedPlantiqIndexRoute
  '/procurement': typeof AuthenticatedProcurementIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/site': typeof AuthenticatedSiteIndexRoute
  '/tender-boq': typeof AuthenticatedTenderBoqIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/maintenance/sites/$siteId': typeof AuthenticatedMaintenanceSitesSiteIdRoute
  '/maintenance/sites': typeof AuthenticatedMaintenanceSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/boq/$boqId': typeof AuthenticatedBoqBoqIdRoute
  '/_authenticated/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/opportunities': typeof AuthenticatedCrmOpportunitiesRoute
  '/_authenticated/crm/tenders': typeof AuthenticatedCrmTendersRoute
  '/_authenticated/design/$designId': typeof AuthenticatedDesignDesignIdRoute
  '/_authenticated/finance/$invoiceId': typeof AuthenticatedFinanceInvoiceIdRoute
  '/_authenticated/jarvis/log': typeof AuthenticatedJarvisLogRoute
  '/_authenticated/maintenance/contracts': typeof AuthenticatedMaintenanceContractsRoute
  '/_authenticated/maintenance/inspections': typeof AuthenticatedMaintenanceInspectionsRoute
  '/_authenticated/maintenance/irrigation': typeof AuthenticatedMaintenanceIrrigationRoute
  '/_authenticated/maintenance/issues': typeof AuthenticatedMaintenanceIssuesRoute
  '/_authenticated/maintenance/schedules': typeof AuthenticatedMaintenanceSchedulesRoute
  '/_authenticated/maintenance/tasks': typeof AuthenticatedMaintenanceTasksRoute
  '/_authenticated/maintenance/templates': typeof AuthenticatedMaintenanceTemplatesRoute
  '/_authenticated/maintenance/treatments': typeof AuthenticatedMaintenanceTreatmentsRoute
  '/_authenticated/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/_authenticated/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/_authenticated/procurement/$poId': typeof AuthenticatedProcurementPoIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/site/$reportId': typeof AuthenticatedSiteReportIdRoute
  '/_authenticated/tender-boq/$tenderBoqId': typeof AuthenticatedTenderBoqTenderBoqIdRoute
  '/_portal/portal/billing': typeof PortalPortalBillingRoute
  '/_portal/portal/bills': typeof PortalPortalBillsRoute
  '/_portal/portal/orders': typeof PortalPortalOrdersRoute
  '/_portal/portal/projects': typeof PortalPortalProjectsRoute
  '/api/public/tenders-ingest': typeof ApiPublicTendersIngestRoute
  '/_authenticated/boq/': typeof AuthenticatedBoqIndexRoute
  '/_authenticated/design/': typeof AuthenticatedDesignIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/jarvis/': typeof AuthenticatedJarvisIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/nursery/': typeof AuthenticatedNurseryIndexRoute
  '/_authenticated/plantiq/': typeof AuthenticatedPlantiqIndexRoute
  '/_authenticated/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/site/': typeof AuthenticatedSiteIndexRoute
  '/_authenticated/tender-boq/': typeof AuthenticatedTenderBoqIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_authenticated/maintenance/sites/$siteId': typeof AuthenticatedMaintenanceSitesSiteIdRoute
  '/_authenticated/maintenance/sites/': typeof AuthenticatedMaintenanceSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/vendor-register'
    | '/approvals'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/api/health'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/employees'
    | '/admin/portal'
    | '/admin/roles'
    | '/admin/users'
    | '/boq/$boqId'
    | '/crm/clients'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/crm/tenders'
    | '/design/$designId'
    | '/finance/$invoiceId'
    | '/jarvis/log'
    | '/maintenance/contracts'
    | '/maintenance/inspections'
    | '/maintenance/irrigation'
    | '/maintenance/issues'
    | '/maintenance/schedules'
    | '/maintenance/tasks'
    | '/maintenance/templates'
    | '/maintenance/treatments'
    | '/masters/materials'
    | '/masters/plants'
    | '/procurement/$poId'
    | '/projects/$projectId'
    | '/site/$reportId'
    | '/tender-boq/$tenderBoqId'
    | '/portal/billing'
    | '/portal/bills'
    | '/portal/orders'
    | '/portal/projects'
    | '/api/public/tenders-ingest'
    | '/boq/'
    | '/design/'
    | '/finance/'
    | '/hr/'
    | '/inventory/'
    | '/jarvis/'
    | '/maintenance/'
    | '/nursery/'
    | '/plantiq/'
    | '/procurement/'
    | '/projects/'
    | '/site/'
    | '/tender-boq/'
    | '/portal/'
    | '/maintenance/sites/$siteId'
    | '/maintenance/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/vendor-register'
    | '/approvals'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/api/health'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/employees'
    | '/admin/portal'
    | '/admin/roles'
    | '/admin/users'
    | '/boq/$boqId'
    | '/crm/clients'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/crm/tenders'
    | '/design/$designId'
    | '/finance/$invoiceId'
    | '/jarvis/log'
    | '/maintenance/contracts'
    | '/maintenance/inspections'
    | '/maintenance/irrigation'
    | '/maintenance/issues'
    | '/maintenance/schedules'
    | '/maintenance/tasks'
    | '/maintenance/templates'
    | '/maintenance/treatments'
    | '/masters/materials'
    | '/masters/plants'
    | '/procurement/$poId'
    | '/projects/$projectId'
    | '/site/$reportId'
    | '/tender-boq/$tenderBoqId'
    | '/portal/billing'
    | '/portal/bills'
    | '/portal/orders'
    | '/portal/projects'
    | '/api/public/tenders-ingest'
    | '/boq'
    | '/design'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/jarvis'
    | '/maintenance'
    | '/nursery'
    | '/plantiq'
    | '/procurement'
    | '/projects'
    | '/site'
    | '/tender-boq'
    | '/portal'
    | '/maintenance/sites/$siteId'
    | '/maintenance/sites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_portal'
    | '/auth'
    | '/vendor-register'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/api/health'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/company'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/portal'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/boq/$boqId'
    | '/_authenticated/crm/clients'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/opportunities'
    | '/_authenticated/crm/tenders'
    | '/_authenticated/design/$designId'
    | '/_authenticated/finance/$invoiceId'
    | '/_authenticated/jarvis/log'
    | '/_authenticated/maintenance/contracts'
    | '/_authenticated/maintenance/inspections'
    | '/_authenticated/maintenance/irrigation'
    | '/_authenticated/maintenance/issues'
    | '/_authenticated/maintenance/schedules'
    | '/_authenticated/maintenance/tasks'
    | '/_authenticated/maintenance/templates'
    | '/_authenticated/maintenance/treatments'
    | '/_authenticated/masters/materials'
    | '/_authenticated/masters/plants'
    | '/_authenticated/procurement/$poId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/site/$reportId'
    | '/_authenticated/tender-boq/$tenderBoqId'
    | '/_portal/portal/billing'
    | '/_portal/portal/bills'
    | '/_portal/portal/orders'
    | '/_portal/portal/projects'
    | '/api/public/tenders-ingest'
    | '/_authenticated/boq/'
    | '/_authenticated/design/'
    | '/_authenticated/finance/'
    | '/_authenticated/hr/'
    | '/_authenticated/inventory/'
    | '/_authenticated/jarvis/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/nursery/'
    | '/_authenticated/plantiq/'
    | '/_authenticated/procurement/'
    | '/_authenticated/projects/'
    | '/_authenticated/site/'
    | '/_authenticated/tender-boq/'
    | '/_portal/portal/'
    | '/_authenticated/maintenance/sites/$siteId'
    | '/_authenticated/maintenance/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPublicTendersIngestRoute: typeof ApiPublicTendersIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-register': {
      id: '/vendor-register'
      path: '/vendor-register'
      fullPath: '/vendor-register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/company': {
      id: '/_authenticated/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AuthenticatedAdminCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/portal': {
      id: '/_authenticated/admin/portal'
      path: '/admin/portal'
      fullPath: '/admin/portal'
      preLoaderRoute: typeof AuthenticatedAdminPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boq/': {
      id: '/_authenticated/boq/'
      path: '/boq'
      fullPath: '/boq/'
      preLoaderRoute: typeof AuthenticatedBoqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boq/$boqId': {
      id: '/_authenticated/boq/$boqId'
      path: '/boq/$boqId'
      fullPath: '/boq/$boqId'
      preLoaderRoute: typeof AuthenticatedBoqBoqIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clients': {
      id: '/_authenticated/crm/clients'
      path: '/crm/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof AuthenticatedCrmClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/opportunities': {
      id: '/_authenticated/crm/opportunities'
      path: '/crm/opportunities'
      fullPath: '/crm/opportunities'
      preLoaderRoute: typeof AuthenticatedCrmOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/tenders': {
      id: '/_authenticated/crm/tenders'
      path: '/crm/tenders'
      fullPath: '/crm/tenders'
      preLoaderRoute: typeof AuthenticatedCrmTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/': {
      id: '/_authenticated/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof AuthenticatedDesignIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/$designId': {
      id: '/_authenticated/design/$designId'
      path: '/design/$designId'
      fullPath: '/design/$designId'
      preLoaderRoute: typeof AuthenticatedDesignDesignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/$invoiceId': {
      id: '/_authenticated/finance/$invoiceId'
      path: '/finance/$invoiceId'
      fullPath: '/finance/$invoiceId'
      preLoaderRoute: typeof AuthenticatedFinanceInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jarvis/': {
      id: '/_authenticated/jarvis/'
      path: '/jarvis'
      fullPath: '/jarvis/'
      preLoaderRoute: typeof AuthenticatedJarvisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jarvis/log': {
      id: '/_authenticated/jarvis/log'
      path: '/jarvis/log'
      fullPath: '/jarvis/log'
      preLoaderRoute: typeof AuthenticatedJarvisLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/contracts': {
      id: '/_authenticated/maintenance/contracts'
      path: '/maintenance/contracts'
      fullPath: '/maintenance/contracts'
      preLoaderRoute: typeof AuthenticatedMaintenanceContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/inspections': {
      id: '/_authenticated/maintenance/inspections'
      path: '/maintenance/inspections'
      fullPath: '/maintenance/inspections'
      preLoaderRoute: typeof AuthenticatedMaintenanceInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/irrigation': {
      id: '/_authenticated/maintenance/irrigation'
      path: '/maintenance/irrigation'
      fullPath: '/maintenance/irrigation'
      preLoaderRoute: typeof AuthenticatedMaintenanceIrrigationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/issues': {
      id: '/_authenticated/maintenance/issues'
      path: '/maintenance/issues'
      fullPath: '/maintenance/issues'
      preLoaderRoute: typeof AuthenticatedMaintenanceIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/schedules': {
      id: '/_authenticated/maintenance/schedules'
      path: '/maintenance/schedules'
      fullPath: '/maintenance/schedules'
      preLoaderRoute: typeof AuthenticatedMaintenanceSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/tasks': {
      id: '/_authenticated/maintenance/tasks'
      path: '/maintenance/tasks'
      fullPath: '/maintenance/tasks'
      preLoaderRoute: typeof AuthenticatedMaintenanceTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/templates': {
      id: '/_authenticated/maintenance/templates'
      path: '/maintenance/templates'
      fullPath: '/maintenance/templates'
      preLoaderRoute: typeof AuthenticatedMaintenanceTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/treatments': {
      id: '/_authenticated/maintenance/treatments'
      path: '/maintenance/treatments'
      fullPath: '/maintenance/treatments'
      preLoaderRoute: typeof AuthenticatedMaintenanceTreatmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/materials': {
      id: '/_authenticated/masters/materials'
      path: '/masters/materials'
      fullPath: '/masters/materials'
      preLoaderRoute: typeof AuthenticatedMastersMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/plants': {
      id: '/_authenticated/masters/plants'
      path: '/masters/plants'
      fullPath: '/masters/plants'
      preLoaderRoute: typeof AuthenticatedMastersPlantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nursery/': {
      id: '/_authenticated/nursery/'
      path: '/nursery'
      fullPath: '/nursery/'
      preLoaderRoute: typeof AuthenticatedNurseryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantiq/': {
      id: '/_authenticated/plantiq/'
      path: '/plantiq'
      fullPath: '/plantiq/'
      preLoaderRoute: typeof AuthenticatedPlantiqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/': {
      id: '/_authenticated/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AuthenticatedProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/$poId': {
      id: '/_authenticated/procurement/$poId'
      path: '/procurement/$poId'
      fullPath: '/procurement/$poId'
      preLoaderRoute: typeof AuthenticatedProcurementPoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site/': {
      id: '/_authenticated/site/'
      path: '/site'
      fullPath: '/site/'
      preLoaderRoute: typeof AuthenticatedSiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site/$reportId': {
      id: '/_authenticated/site/$reportId'
      path: '/site/$reportId'
      fullPath: '/site/$reportId'
      preLoaderRoute: typeof AuthenticatedSiteReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tender-boq/': {
      id: '/_authenticated/tender-boq/'
      path: '/tender-boq'
      fullPath: '/tender-boq/'
      preLoaderRoute: typeof AuthenticatedTenderBoqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tender-boq/$tenderBoqId': {
      id: '/_authenticated/tender-boq/$tenderBoqId'
      path: '/tender-boq/$tenderBoqId'
      fullPath: '/tender-boq/$tenderBoqId'
      preLoaderRoute: typeof AuthenticatedTenderBoqTenderBoqIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/billing': {
      id: '/_portal/portal/billing'
      path: '/portal/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalPortalBillingRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/bills': {
      id: '/_portal/portal/bills'
      path: '/portal/bills'
      fullPath: '/portal/bills'
      preLoaderRoute: typeof PortalPortalBillsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/orders': {
      id: '/_portal/portal/orders'
      path: '/portal/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalPortalOrdersRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/portal/projects': {
      id: '/_portal/portal/projects'
      path: '/portal/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalPortalProjectsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/public/tenders-ingest': {
      id: '/api/public/tenders-ingest'
      path: '/api/public/tenders-ingest'
      fullPath: '/api/public/tenders-ingest'
      preLoaderRoute: typeof ApiPublicTendersIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maintenance/sites/': {
      id: '/_authenticated/maintenance/sites/'
      path: '/maintenance/sites'
      fullPath: '/maintenance/sites/'
      preLoaderRoute: typeof AuthenticatedMaintenanceSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/sites/$siteId': {
      id: '/_authenticated/maintenance/sites/$siteId'
      path: '/maintenance/sites/$siteId'
      fullPath: '/maintenance/sites/$siteId'
      preLoaderRoute: typeof AuthenticatedMaintenanceSitesSiteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCompanyRoute: typeof AuthenticatedAdminCompanyRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminPortalRoute: typeof AuthenticatedAdminPortalRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBoqBoqIdRoute: typeof AuthenticatedBoqBoqIdRoute
  AuthenticatedCrmClientsRoute: typeof AuthenticatedCrmClientsRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmOpportunitiesRoute: typeof AuthenticatedCrmOpportunitiesRoute
  AuthenticatedCrmTendersRoute: typeof AuthenticatedCrmTendersRoute
  AuthenticatedDesignDesignIdRoute: typeof AuthenticatedDesignDesignIdRoute
  AuthenticatedFinanceInvoiceIdRoute: typeof AuthenticatedFinanceInvoiceIdRoute
  AuthenticatedJarvisLogRoute: typeof AuthenticatedJarvisLogRoute
  AuthenticatedMaintenanceContractsRoute: typeof AuthenticatedMaintenanceContractsRoute
  AuthenticatedMaintenanceInspectionsRoute: typeof AuthenticatedMaintenanceInspectionsRoute
  AuthenticatedMaintenanceIrrigationRoute: typeof AuthenticatedMaintenanceIrrigationRoute
  AuthenticatedMaintenanceIssuesRoute: typeof AuthenticatedMaintenanceIssuesRoute
  AuthenticatedMaintenanceSchedulesRoute: typeof AuthenticatedMaintenanceSchedulesRoute
  AuthenticatedMaintenanceTasksRoute: typeof AuthenticatedMaintenanceTasksRoute
  AuthenticatedMaintenanceTemplatesRoute: typeof AuthenticatedMaintenanceTemplatesRoute
  AuthenticatedMaintenanceTreatmentsRoute: typeof AuthenticatedMaintenanceTreatmentsRoute
  AuthenticatedMastersMaterialsRoute: typeof AuthenticatedMastersMaterialsRoute
  AuthenticatedMastersPlantsRoute: typeof AuthenticatedMastersPlantsRoute
  AuthenticatedProcurementPoIdRoute: typeof AuthenticatedProcurementPoIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedSiteReportIdRoute: typeof AuthenticatedSiteReportIdRoute
  AuthenticatedTenderBoqTenderBoqIdRoute: typeof AuthenticatedTenderBoqTenderBoqIdRoute
  AuthenticatedBoqIndexRoute: typeof AuthenticatedBoqIndexRoute
  AuthenticatedDesignIndexRoute: typeof AuthenticatedDesignIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedJarvisIndexRoute: typeof AuthenticatedJarvisIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedNurseryIndexRoute: typeof AuthenticatedNurseryIndexRoute
  AuthenticatedPlantiqIndexRoute: typeof AuthenticatedPlantiqIndexRoute
  AuthenticatedProcurementIndexRoute: typeof AuthenticatedProcurementIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSiteIndexRoute: typeof AuthenticatedSiteIndexRoute
  AuthenticatedTenderBoqIndexRoute: typeof AuthenticatedTenderBoqIndexRoute
  AuthenticatedMaintenanceSitesSiteIdRoute: typeof AuthenticatedMaintenanceSitesSiteIdRoute
  AuthenticatedMaintenanceSitesIndexRoute: typeof AuthenticatedMaintenanceSitesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCompanyRoute: AuthenticatedAdminCompanyRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminPortalRoute: AuthenticatedAdminPortalRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBoqBoqIdRoute: AuthenticatedBoqBoqIdRoute,
  AuthenticatedCrmClientsRoute: AuthenticatedCrmClientsRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmOpportunitiesRoute: AuthenticatedCrmOpportunitiesRoute,
  AuthenticatedCrmTendersRoute: AuthenticatedCrmTendersRoute,
  AuthenticatedDesignDesignIdRoute: AuthenticatedDesignDesignIdRoute,
  AuthenticatedFinanceInvoiceIdRoute: AuthenticatedFinanceInvoiceIdRoute,
  AuthenticatedJarvisLogRoute: AuthenticatedJarvisLogRoute,
  AuthenticatedMaintenanceContractsRoute:
    AuthenticatedMaintenanceContractsRoute,
  AuthenticatedMaintenanceInspectionsRoute:
    AuthenticatedMaintenanceInspectionsRoute,
  AuthenticatedMaintenanceIrrigationRoute:
    AuthenticatedMaintenanceIrrigationRoute,
  AuthenticatedMaintenanceIssuesRoute: AuthenticatedMaintenanceIssuesRoute,
  AuthenticatedMaintenanceSchedulesRoute:
    AuthenticatedMaintenanceSchedulesRoute,
  AuthenticatedMaintenanceTasksRoute: AuthenticatedMaintenanceTasksRoute,
  AuthenticatedMaintenanceTemplatesRoute:
    AuthenticatedMaintenanceTemplatesRoute,
  AuthenticatedMaintenanceTreatmentsRoute:
    AuthenticatedMaintenanceTreatmentsRoute,
  AuthenticatedMastersMaterialsRoute: AuthenticatedMastersMaterialsRoute,
  AuthenticatedMastersPlantsRoute: AuthenticatedMastersPlantsRoute,
  AuthenticatedProcurementPoIdRoute: AuthenticatedProcurementPoIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedSiteReportIdRoute: AuthenticatedSiteReportIdRoute,
  AuthenticatedTenderBoqTenderBoqIdRoute:
    AuthenticatedTenderBoqTenderBoqIdRoute,
  AuthenticatedBoqIndexRoute: AuthenticatedBoqIndexRoute,
  AuthenticatedDesignIndexRoute: AuthenticatedDesignIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedJarvisIndexRoute: AuthenticatedJarvisIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedNurseryIndexRoute: AuthenticatedNurseryIndexRoute,
  AuthenticatedPlantiqIndexRoute: AuthenticatedPlantiqIndexRoute,
  AuthenticatedProcurementIndexRoute: AuthenticatedProcurementIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSiteIndexRoute: AuthenticatedSiteIndexRoute,
  AuthenticatedTenderBoqIndexRoute: AuthenticatedTenderBoqIndexRoute,
  AuthenticatedMaintenanceSitesSiteIdRoute:
    AuthenticatedMaintenanceSitesSiteIdRoute,
  AuthenticatedMaintenanceSitesIndexRoute:
    AuthenticatedMaintenanceSitesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalPortalBillingRoute: typeof PortalPortalBillingRoute
  PortalPortalBillsRoute: typeof PortalPortalBillsRoute
  PortalPortalOrdersRoute: typeof PortalPortalOrdersRoute
  PortalPortalProjectsRoute: typeof PortalPortalProjectsRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPortalBillingRoute: PortalPortalBillingRoute,
  PortalPortalBillsRoute: PortalPortalBillsRoute,
  PortalPortalOrdersRoute: PortalPortalOrdersRoute,
  PortalPortalProjectsRoute: PortalPortalProjectsRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPublicTendersIngestRoute: ApiPublicTendersIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
